# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# specific path build
trigger:
  branches:
    include:
    - feature-*
  paths:
    include:
    - apis/user-java/*

pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: buildandtests
  displayName: Build and Test
  jobs: 
  - job: buildandtestj
    displayName: Build and Test
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: './apis/user-java/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job: createitem
    displayName: Create Item
    dependsOn: buildandtestj
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        inputs:
          workItemType: 'Issue'
          title: 'Build failure for commit $(Build.SourceVersion)'
          associate: true
          description: 'This is automated work for failing build. Latest commit message: $(Build.SourceVersionMessage)'
