# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - feature-*
  paths:
    include:
    - apis/trips/*

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: buildandtests
  displayName: Build and Test
  jobs: 
  - job: buildandtestj
    displayName: Build and Test
    steps:
    - task: GoTool@0
      inputs:
        version: '1.13.5'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/tests'
      
    - task: CopyFiles@2
      inputs:
        TargetFolder: '$(Build.ArtifactStagingDirectory)/apis/trips'
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: drop

  - job: createitem
    displayName: Create Item
    dependsOn: buildandtestj
    condition: failed() # this job will only run if rununittest fails
    steps:
      - task: CreateWorkItem@1
        inputs:
          workItemType: 'Issue'
          title: 'Trips Build failure for commit $(Build.SourceVersion)'
          associate: true
          description: 'This is automated work for failing build. Latest commit message: $(Build.SourceVersionMessage)'
