# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ shirihhhh-patch-1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    # The type of runner that the job will run on
      build_and_test:
        runs-on: ubuntu-latest
        defaults:
          run: 
            shell: bash
            working-directory: apis/trips
        steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v2
          - uses: actions/setup-go@v2
            with:
             go-version: '1.12.0'
          - run: |
              go version
              go get  
          - run: go build .
          - run: go test ./tests
